export type Activity = {
  slug: string;
  short: string;
  icon: string;
  title: string;
  summary: string;
  intro: string;
  details: string[];
  topics: string[];
  meeting: [string, string][];
  leader?: string;
  tone: string;
  category: string;
};

export const activities: Activity[] = [
  {
    slug: 'kreativ',
    short: 'KR',
    icon: '✎',
    title: 'Kreativ',
    summary: 'Gemeinsam gestalten, handarbeiten und neue Ideen ausprobieren.',
    intro: 'Basteln war früher – heute heißt es kreativ sein. Denn kreativ sein bedeutet, das Leben mit eigenen Ideen zu gestalten.',
    details: ['In unserer Kreativgruppe entstehen in geselliger Runde kleine und große Projekte. Eigene Ideen sind ausdrücklich willkommen.', 'Vorkenntnisse sind nicht nötig. Freude am Gestalten und am Austausch genügt.'],
    topics: ['Handarbeiten und Bastelprojekte', 'Saisonale Dekorationen', 'Ideen miteinander teilen'],
    meeting: [['Donnerstag', '13:30–16:00 Uhr']],
    leader: 'B. Dreesen',
    tone: 'coral',
    category: 'Kreativität',
  },
  {
    slug: 'kartenspiel',
    short: 'KA',
    icon: '♣',
    title: 'Kartenspiel',
    summary: 'Klassische Kartenspiele lernen und in geselliger Runde spielen.',
    intro: 'Unsere Freizeitstätte wird zur kleinen Spielhölle – natürlich nur im besten Sinne. Hier geht es um Freude am Spiel und gute Gesellschaft.',
    details: ['Ob bekannte Regeln auffrischen oder ein neues Spiel kennenlernen: In der Gruppe findet sich schnell die passende Runde.', 'Gespielt wird konzentriert, aber immer mit Humor und einer gemütlichen Pause zwischendurch.'],
    topics: ['Skat und weitere Kartenspiele', 'Regeln gemeinsam lernen', 'Geselligkeit und Spielfreude'],
    meeting: [['Montag', '14:00–17:00 Uhr']],
    leader: 'M. Keil',
    tone: 'gold',
    category: 'Spiel & Begegnung',
  },
  {
    slug: 'gymnastik',
    short: 'GY',
    icon: '◉',
    title: 'Gymnastik',
    summary: 'Mit Musik und Bewegung beweglich und sicher im Alltag bleiben.',
    intro: 'Musik und Bewegung bringen Schwung in die Woche und helfen dabei, Gelenke und Muskulatur möglichst lange beweglich zu halten.',
    details: ['Die Übungen sind auf die Möglichkeiten der Teilnehmenden abgestimmt und werden gemeinsam in ruhigem Tempo durchgeführt.', 'Bequeme Kleidung und Freude an Bewegung reichen für den Einstieg aus.'],
    topics: ['Sanfte Mobilisation', 'Koordination und Gleichgewicht', 'Bewegung in der Gruppe'],
    meeting: [['Montag', '09:30–10:30 Uhr']],
    leader: 'S. Lück',
    tone: 'green',
    category: 'Bewegung',
  },
  {
    slug: 'tischtennis',
    short: 'TT',
    icon: '●',
    title: 'Tischtennis',
    summary: 'Sport, Reaktion und jede Menge Spaß mit dem kleinen Ball.',
    intro: 'Ping – Pong – Ping – Pong: Wir machen das Spiel mit dem kleinen Ball zum sportlichen Erlebnis und haben viel Spaß dabei.',
    details: ['Mehrere Gruppen bieten über die Woche verteilt passende Spielzeiten. So bleibt genug Raum für Bewegung, Training und gemeinsame Matches.', 'Neue Mitspielerinnen und Mitspieler melden sich am besten kurz vorab, damit wir die passende Gruppe empfehlen können.'],
    topics: ['Reaktion und Beweglichkeit', 'Freundschaftliche Spiele', 'Drei Gruppen pro Woche'],
    meeting: [['Montag', '09:00–13:00 Uhr'], ['Dienstag', '11:00–16:00 Uhr'], ['Mittwoch', '09:00–12:00 Uhr'], ['Donnerstag', '09:00–13:00 Uhr']],
    leader: 'M. Pliet, M. Plangger und H. Mirsch',
    tone: 'green',
    category: 'Bewegung',
  },
  {
    slug: 'englisch',
    short: 'EN',
    icon: 'Aa',
    title: 'Englisch',
    summary: 'Sprachkenntnisse auffrischen und gemeinsam sicherer sprechen.',
    intro: 'How do you do? Bei uns zählt „Ich verstehe nur Bahnhof“ nicht – wir frischen Englisch gemeinsam und ohne Leistungsdruck auf.',
    details: ['Im Mittelpunkt stehen praktische Sprache, Wiederholung und das freie Sprechen in angenehmer Atmosphäre.', 'Das gemeinsame Lernen hält geistig fit und macht in der Gruppe besonders viel Freude.'],
    topics: ['Alltagsenglisch', 'Wortschatz und Aussprache', 'Sprechen in entspannter Runde'],
    meeting: [['Mittwoch', '10:00–12:00 Uhr']],
    leader: 'D. Odorinszky',
    tone: 'violet',
    category: 'Sprache',
  },
  {
    slug: 'schach',
    short: 'SC',
    icon: '♞',
    title: 'Schach',
    summary: 'Geistige Fitness, schöne Kombinationen und gemeinsame Partien.',
    intro: 'Schach ist eines der komplexesten Brettspiele und ein ideales Training für Gedächtnis, Konzentration und räumliches Vorstellungsvermögen.',
    details: ['Freitags wird mit Eifer um den Sieg gerungen – aber eine schöne Partie und der Spaß am Spiel sind wichtiger als das Ergebnis.', 'Nach einer Partie folgt oft eine kurze gemeinsame Analyse. Kaffee, Gebäck und der gemütliche Teil kommen ebenfalls nicht zu kurz. Etwas Spielerfahrung ist hilfreich.'],
    topics: ['Partien untereinander', 'Gemeinsame Spielanalyse', 'Training für Konzentration und Gedächtnis'],
    meeting: [['Freitag', '14:30–18:00 Uhr']],
    leader: 'E. Brandl',
    tone: 'gold',
    category: 'Spiel & Begegnung',
  },
  {
    slug: 'pc-im-alltag',
    short: 'PC',
    icon: '⌘',
    title: 'PC im Alltag',
    summary: 'Alltägliche Computerfragen gemeinsam lösen und Neues entdecken.',
    intro: 'Der Computer gehört heute zum Alltag. In der Gruppe können Mitglieder ihre täglichen Fragen zur Sprache bringen und voneinander lernen.',
    details: ['Der Austausch bringt neue Anregungen – von Windows und Software bis zu sicheren Passwörtern und individuellen Einstellungen.', 'Learning by doing steht im Mittelpunkt: ausprobieren, wiederholen und sich gegenseitig helfen.'],
    topics: ['Windows und Software', 'Sicherheit und Passwörter', 'Praktische Hilfe bei PC-Problemen'],
    meeting: [['Dienstag', '16:00–18:00 Uhr']],
    tone: 'blue',
    category: 'Computer & Technik',
  },
  {
    slug: 'pc-anfaenger',
    short: 'PA',
    icon: '⌘',
    title: 'PC Anfänger & Fortgeschrittene',
    summary: 'Den Computer von Grund auf verstehen oder vorhandenes Wissen vertiefen.',
    intro: 'Es gibt immer ein erstes Mal. Hier lernen Einsteigerinnen und Einsteiger den Computer in verständlichen Schritten kennen.',
    details: ['Fortgeschrittene bringen konkrete Fragen zu Windows, Programmen oder ihrem eigenen Gerät mit.', 'Das Tempo richtet sich nach der Gruppe. Fragen sind jederzeit willkommen.'],
    topics: ['Computer-Grundlagen', 'Windows und Programme', 'Probleme gemeinsam lösen'],
    meeting: [['Mittwoch', '12:00–16:00 Uhr'], ['Freitag', '10:00–12:00 Uhr']],
    leader: 'H. Hönig',
    tone: 'blue',
    category: 'Computer & Technik',
  },
  {
    slug: 'excel',
    short: 'EX',
    icon: '▦',
    title: 'Excel',
    summary: 'Tabellen, Berechnungen und praktische Aufgaben verständlich lösen.',
    intro: 'Zahlen, Tabellen und Berechnungen begegnen uns überall. Gemeinsam erschließen wir die Möglichkeiten von Microsoft Excel.',
    details: ['An praktischen Beispielen werden Tabellen aufgebaut, Formeln eingesetzt und Ergebnisse übersichtlich dargestellt.', 'Eigene Aufgaben und Fragen können gerne mitgebracht werden.'],
    topics: ['Tabellen sinnvoll aufbauen', 'Formeln und Berechnungen', 'Praktische Alltagsaufgaben'],
    meeting: [['Montag', '11:00–13:00 Uhr']],
    leader: 'W. Weidauer',
    tone: 'blue',
    category: 'Computer & Technik',
  },
  {
    slug: 'smartphone',
    short: 'SM',
    icon: '📱',
    title: 'Smartphone & Tablet',
    summary: 'Sicherer mit Smartphone, iPhone und iPad umgehen.',
    intro: 'Das Smartphone ist das meistgenutzte Kommunikationsmittel. Wir machen Sie Schritt für Schritt fit für den Alltag.',
    details: ['Die Gesprächskreise greifen aktuelle Fragen auf: Nachrichten, Fotos, Apps, Einstellungen und Sicherheit.', 'Für iPhone und iPad gibt es zusätzlich einen eigenen monatlichen Termin.'],
    topics: ['Bedienung und Einstellungen', 'Apps, Fotos und Nachrichten', 'Sicherheit und Datenschutz'],
    meeting: [['Smartphone', '2. + 4. Dienstag, 12:30–15:30 Uhr'], ['iPhone/iPad', '1. Samstag, 10:00–12:45 Uhr']],
    leader: 'B. Baasner und P. Freiberg',
    tone: 'mint',
    category: 'Computer & Technik',
  },
  {
    slug: 'videogruppe',
    short: 'VI',
    icon: '▶',
    title: 'Videogruppe',
    summary: 'Eigene Aufnahmen drehen, schneiden und als Film gestalten.',
    intro: 'Die Videogruppe beschäftigt sich mit Videoschnitt am PC. Auch Aufnahmen vom Smartphone eignen sich hervorragend für eigene Filmprojekte.',
    details: ['Im Club steht ein kleines Studio zur Verfügung. Dort werden Szenen gedreht und anschließend gemeinsam am Computer bearbeitet.', 'Vorkenntnisse sind nicht erforderlich. Im Mittelpunkt stehen Neugier, gemeinsames Lernen und Freude am fertigen Film.'],
    topics: ['Aufnahmen mit Kamera oder Smartphone', 'Videoschnitt am PC', 'Gemeinsame Filmprojekte'],
    meeting: [['Dienstag', '09:30–12:00 Uhr']],
    leader: 'W. Reek',
    tone: 'violet',
    category: 'Computer & Technik',
  },
  {
    slug: 'wandern',
    short: 'WA',
    icon: '🥾',
    title: 'Wandern',
    summary: 'Natur, Bewegung und gute Gespräche im Berliner Norden.',
    intro: 'Unsere Wandergruppe ist rund um das Fließtal zwischen Glienicke und dem Freizeitpark Lübars unterwegs.',
    details: ['Uns verbinden das Interesse an der Natur und die Freude an anregenden oder einfach spaßigen Gesprächen. Eine gemütliche Einkehr gehört oft dazu.', 'Daneben besuchen wir andere Teile Berlins, Ausstellungen und Museen. Die jeweilige Route wird vorab in der Gruppe vereinbart.'],
    topics: ['Touren im Berliner Norden', 'Ausflüge und Kultur', 'Gemeinschaft bei Wind und Wetter'],
    meeting: [['Freitag', '13:30–17:00 Uhr'], ['Treffpunkt', 'nach Absprache']],
    leader: 'J. Lentz',
    tone: 'green',
    category: 'Draußen aktiv',
  },
  {
    slug: 'fahrradtouren',
    short: 'RA',
    icon: '🚲',
    title: 'Fahrradtouren',
    summary: 'Mit dem Rad gemeinsam die Natur unserer Umgebung erleben.',
    intro: 'Mit dem Rad geht es durch die grüne Umgebung von Lübars und in den Berliner Norden – für alle, die gerne gemeinsam unterwegs sind.',
    details: ['Strecke, Treffpunkt und Tempo werden passend zur geplanten Tour abgestimmt.', 'Interessierte melden sich bitte vorab, damit wir über den nächsten Termin informieren können.'],
    topics: ['Touren in die Umgebung', 'Bewegung an der frischen Luft', 'Termine nach gemeinsamer Absprache'],
    meeting: [['Termine', 'Nach Ankündigung und Absprache']],
    tone: 'green',
    category: 'Draußen aktiv',
  },
];

export const getActivity = (slug: string) => activities.find(activity => activity.slug === slug);
